[project]
name = 'Asteroid-Mining-Simulation-and-Investment'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.asteroid-mining-nft]
path = 'contracts/asteroid-mining-nft.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
