[project]
name = 'Asteroid-Mining-Simulation-and-Investment'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.asteroid-mining-nft]
path = 'contracts/asteroid-mining-nft.clar'
clarity_version = 2
epoch = 2.5

[contracts.governance]
path = 'contracts/governance.clar'
clarity_version = 2
epoch = 2.5

[contracts.mining-simulation]
path = 'contracts/mining-simulation.clar'
clarity_version = 2
epoch = 2.5

[contracts.resource-market]
path = 'contracts/resource-market.clar'
clarity_version = 2
epoch = 2.5

[contracts.space-data-oracle]
path = 'contracts/space-data-oracle.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
